### ISSUE TITLE
CT: Cannot read properties of null (reading 'transformMatrix')

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#24]
```
models-of-the-hydrogen-atom : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653496821904/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653496821904%22%2C%22timestamp%22%3A1653501460642%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'transformMatrix')
TypeError: Cannot read properties of null (reading 'transformMatrix')
at transformMatrix (RectangleCanvasDrawable.js:102:35)
at paintCanvas (Rectangle.ts:725:38)
at canvasPaintSelf (Node.ts:5276:11)
at renderToCanvasSelf (Node.ts:5291:9)
at renderToCanvasSubtree (Node.ts:5342:16)
at renderToCanvasSubtree (Node.ts:5310:16)
at renderToCanvasSubtree (Node.ts:5342:16)
at renderToCanvasSubtree (Node.ts:5342:16)
at renderToCanvasSubtree (Node.ts:5342:16)
at renderToCanvasSubtree (Node.ts:5342:16)
id: Bayes Chrome
Snapshot from 5/25/2022, 10:40:21 AM
```

**Comment by pixelzoom** [comment]
Reproduced locally with `?brand=phet&ea&debugger&initialScreen=1&fuzz`, with this stack trace:

```
RectangleCanvasDrawable.js? [sm]:102 Uncaught TypeError: Cannot read properties of null (reading 'transformMatrix')
    at CanvasSelfDrawable.paintCanvas (RectangleCanvasDrawable.js? [sm]:102:14)
    at Rectangle.canvasPaintSelf (Rectangle.ts:725:39)
    at Rectangle.renderToCanvasSelf (Node.ts:5276:12)
    at Rectangle.renderToCanvasSubtree (Node.ts:5291:10)
    at Node.renderToCanvasSubtree (Node.ts:5342:17)
    at AlignBox.renderToCanvasSubtree (Node.ts:5342:17)
    at RectangularRadioButton.renderToCanvasSubtree (Node.ts:5342:17)
    at LightModeRadioButtonGroup.renderToCanvasSubtree (Node.ts:5342:17)
    at Node.renderToCanvasSubtree (Node.ts:5342:17)
    at SpectraScreenView.renderToCanvasSubtree (Node.ts:5342:17)
```

**Comment by jonathanolson** [comment]
Definite bug. `hasFill()`/`hasStroke()` should not be returning true if it's a Property with a null value. Seeing if the fix breaks anything.

**Comment by pixelzoom** [comment]
I haven't seen any problems in the sim or in CT.  @jonathanolson can this issue be closed?

**Comment by jonathanolson** [comment]
Yes, thanks!
