### ISSUE TITLE
CT: Emitters must include phetioType for each parameter or be marked as `phetioPrivate`

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/models-of-the-hydrogen-atom#25]
```
models-of-the-hydrogen-atom : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653505632484%22%2C%22timestamp%22%3A1653508160254%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: instrumented Emitters must include phetioType for each parameter or be marked as `phetioPrivate`.
Error: Assertion failed: instrumented Emitters must include phetioType for each parameter or be marked as `phetioPrivate`.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/assert/js/assert.js:28:13)
at assert (PhetioDataHandler.ts:130:55)
at validateParameters (PhetioDataHandler.ts:77:32)
at (Emitter.ts:48:4)
at (HydrogenAtomModel.ts:76:33)
at (BilliardBallModel.ts:56:4)
at (SpectraModel.ts:39:30)
at (SpectraScreen.ts:30:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:842:15)
id: Bayes Chrome
Snapshot from 5/25/2022, 1:07:12 PM

----------------------------------

models-of-the-hydrogen-atom : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/studio/?sim=models-of-the-hydrogen-atom&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653505632484%22%2C%22timestamp%22%3A1653507127394%7D
Uncaught Error: Uncaught Error: Assertion failed: instrumented Emitters must include phetioType for each parameter or be marked as `phetioPrivate`.
Error: Assertion failed: instrumented Emitters must include phetioType for each parameter or be marked as `phetioPrivate`.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/assert/js/assert.js:28:13)
at assert (PhetioDataHandler.ts:130:55)
at validateParameters (PhetioDataHandler.ts:77:32)
at (Emitter.ts:48:4)
at (HydrogenAtomModel.ts:76:33)
at (BilliardBallModel.ts:56:4)
at (SpectraModel.ts:39:30)
at (SpectraScreen.ts:30:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:842:15)
id: Bayes Chrome
Snapshot from 5/25/2022, 1:07:12 PM

----------------------------------

models-of-the-hydrogen-atom : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/phet-io-wrappers/phet-io-wrappers-tests.html?sim=models-of-the-hydrogen-atom
22 out of 24 tests passed. 2 failed.
CrossFrameMessageTests: models-of-the-hydrogen-atom: test multiple launchSimulation calls failed:
timeout on test, unable to complete test
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/chipper/dist/js/phet-io-wrappers/js/tests/CrossFrameMessageTests.js:124:14

SimTests: models-of-the-hydrogen-atom: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: instrumented Emitters must include phetioType for each parameter or be marked as `phetioPrivate`.
Error: Assertion failed: instrumented Emitters must include phetioType for each parameter or be marked as `phetioPrivate`.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/assert/js/assert.js:28:13)
at PhetioDataHandler.validateParameters (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/chipper/dist/js/tandem/js/PhetioDataHandler.js:91:56)
at new PhetioDataHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/chipper/dist/js/tandem/js/PhetioDataHandler.js:49:33)
at new Emitter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/chipper/dist/js/axon/js/Emitter.js:30:5)
at new HydrogenAtomModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/HydrogenAtomModel.js:43:34)
at new BilliardBallModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/BilliardBallModel.js:38:5)
at new SpectraModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/chipper/dist/js/models-of-the-hydrogen-atom/js/spectra/model/SpectraModel.js:22:31)
at SpectraScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/chipper/dist/js/models-of-the-hydrogen-atom/js/spectra/SpectraScreen.js:20:17)
at SpectraScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/chipper/dist/js/joist/js/Screen.js:197:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/chipper/dist/js/joist/js/Sim.js:632:16)

Uncaught Error: Uncaught Error: Assertion failed: instrumented Emitters must include phetioType for each parameter or be marked as `phetioPrivate`.Error: Assertion failed: instrumented Emitters must include phetioType for each parameter or be marked as `phetioPrivate`.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653505632484/assert/js/assert.js:28:13)
at assert (PhetioDataHandler.ts:130:55)
at validateParameters (PhetioDataHandler.ts:77:32)
at (Emitter.ts:48:4)
at (HydrogenAtomModel.ts:76:33)
at (BilliardBallModel.ts:56:4)
at (SpectraModel.ts:39:30)
at (SpectraScreen.ts:30:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:842:15)
id: Bayes Chrome
Snapshot from 5/25/2022, 1:07:12 PM
```

**Comment by pixelzoom** [comment]
Fixed in the above commit by uninstrumenting Emitters.  Verified in my working copy with:
`models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?brand=phet-io&phetioStandalone&ea&fuzz&debugger`

I'll leave this open until I've verified that CT is happy.
