### ISSUE TITLE
Assertion failure in PlumPuddingModel.moveElectron

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#27]
I'm in the middle of porting PlumPuddingModel, so this is not a big deal. But I figured I'd proactively create an issue, in case it shows up in CT.  

```
assert.js:28 Uncaught Error: Assertion failed
    at window.assertions.assertFunction (assert.js:28:13)
    at PlumPuddingModel.moveElectron (PlumPuddingModel.ts:250:15)
    at PlumPuddingModel.step (PlumPuddingModel.ts:311:12)
    at SpectraModel.stepPrivate (MOTHAModel.ts:195:37)
    at SpectraModel.step (MOTHAModel.ts:176:12)
    at Sim.ts:447:22
    at PhetioAction.execute (PhetioAction.ts:124:17)
    at Sim.stepSimulation (Sim.ts:990:31)
    at Sim.stepOneFrame (Sim.ts:980:12)
    at Sim.runAnimationLoop (Sim.ts:955:12)
```

Relevant code in PlumPuddingModel.ts:

```typescript
  private moveElectron( dt: number, amplitude: number ): void {

    const endpoint1 = this.electronLineEndpoint1Property.value;
    const endpoint2 = this.electronLineEndpoint2Property.value;

    // Assumptions about the electron's oscillation line
250 assert && assert( endpoint1.x < endpoint2.x );
```

**Comment by pixelzoom** [comment]
Fixed, closing.
