### ISSUE TITLE
CT: required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/models-of-the-hydrogen-atom#37]
```
models-of-the-hydrogen-atom : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657703727614%22%2C%22timestamp%22%3A1657709108425%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:209:16)
at initializePhetioObject (PhetioObject.ts:181:11)
at (ReadOnlyProperty.ts:127:4)
at (Property.ts:18:4)
at (BooleanProperty.ts:42:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:63:54)
at (ButtonModel.ts:105:4)
at (PushButtonModel.ts:70:4)
id: Bayes Puppeteer
Snapshot from 7/13/2022, 3:15:27 AM

----------------------------------

models-of-the-hydrogen-atom : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657703727614%22%2C%22timestamp%22%3A1657715831036%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:209:16)
at initializePhetioObject (PhetioObject.ts:181:11)
at (ReadOnlyProperty.ts:127:4)
at (Property.ts:18:4)
at (BooleanProperty.ts:42:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:63:54)
at (ButtonModel.ts:105:4)
at (PushButtonModel.ts:70:4)
id: Bayes Puppeteer
Snapshot from 7/13/2022, 3:15:27 AM

----------------------------------

models-of-the-hydrogen-atom : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/phet-io-wrappers/phet-io-wrappers-tests.html?sim=models-of-the-hydrogen-atom&phetioDebug=true&phetioWrapperDebug=true
27 out of 28 tests passed. 1 failed.
SimTests: models-of-the-hydrogen-atom: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/assert/js/assert.js:28:13)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/tandem/js/PhetioObject.js:140:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/tandem/js/PhetioObject.js:113:12)
at new ReadOnlyProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/axon/js/ReadOnlyProperty.js:75:5)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/axon/js/Property.js:12:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/axon/js/BooleanProperty.js:30:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/axon/js/EnabledProperty.js:29:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/axon/js/EnabledComponent.js:29:55)
at new ButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/sun/js/buttons/ButtonModel.js:54:5)
at new PushButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/sun/js/buttons/PushButtonModel.js:32:5)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:209:16)
at initializePhetioObject (PhetioObject.ts:181:11)
at (ReadOnlyProperty.ts:127:4)
at (Property.ts:18:4)
at (BooleanProperty.ts:42:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:63:54)
at (ButtonModel.ts:105:4)
at (PushButtonModel.ts:70:4)
id: Bayes Puppeteer
Snapshot from 7/13/2022, 3:15:27 AM

----------------------------------

models-of-the-hydrogen-atom : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/phet-io-wrappers/phet-io-wrappers-tests.html?sim=models-of-the-hydrogen-atom
25 out of 26 tests passed. 1 failed.
SimTests: models-of-the-hydrogen-atom: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/assert/js/assert.js:28:13)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/tandem/js/PhetioObject.js:140:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/tandem/js/PhetioObject.js:113:12)
at new ReadOnlyProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/axon/js/ReadOnlyProperty.js:75:5)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/axon/js/Property.js:12:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/axon/js/BooleanProperty.js:30:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/axon/js/EnabledProperty.js:29:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/axon/js/EnabledComponent.js:29:55)
at new ButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/sun/js/buttons/ButtonModel.js:54:5)
at new PushButtonModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/chipper/dist/js/sun/js/buttons/PushButtonModel.js:32:5)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657703727614/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:209:16)
at initializePhetioObject (PhetioObject.ts:181:11)
at (ReadOnlyProperty.ts:127:4)
at (Property.ts:18:4)
at (BooleanProperty.ts:42:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:63:54)
at (ButtonModel.ts:105:4)
at (PushButtonModel.ts:70:4)
id: Bayes Puppeteer
Snapshot from 7/13/2022, 3:15:27 AM
```

**Comment by pixelzoom** [comment]
Fixed in the above commit. Closing.
