### ISSUE TITLE
CT required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/models-of-the-hydrogen-atom#52]
```
models-of-the-hydrogen-atom : phet-io-active-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/phet-io-wrappers/active/?sim=models-of-the-hydrogen-atom&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723654930805%22%2C%22timestamp%22%3A1723655401520%7D
ERROR: Uncaught Error: Assertion failed: required tandems must be supplied
STACK: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/assert/js/assert.js:45:13)
    at assert (PhetioObject.ts:216:6)
    at initializePhetioObject (PhetioObject.ts:196:11)
    at  (ReadOnlyProperty.ts:176:4)
    at  (Property.ts:17:4)
    at  (BooleanProperty.ts:31:4)
    at  (EnabledProperty.ts:45:4)
    at  (EnabledComponent.ts:68:54)
    at  (ButtonModel.ts:108:4)
    at  (PushButtonModel.ts:80:4)
    at  (RectangularPushButton.ts:50:28)
    at  (AbsorptionWavelengthsDialog.ts:101:25)
    at  (LightControlPanel.ts:51:40)
    at  (SpectraScreenView.ts:62:30)
    at  (SpectraScreen.ts:40:15)
    at createView (Screen.ts:309:22)
    at initializeView (Sim.ts:914:15)
    at  (Sim.ts:922:25)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723654930805%2Fphet-io-wrappers%2Factive%2F%3Fsim%3Dmodels-of-the-hydrogen-atom%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723654930805%22%2C%22timestamp%22%3A1723655401520%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723654930805%2Fphet-io-wrappers%2Factive%2F%3Fsim%3Dmodels-of-the-hydrogen-atom%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723654930805%22%2C%22timestamp%22%3A1723655401520%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/phet-io-wrappers/active/?sim=models-of-the-hydrogen-atom&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723654930805%22%2C%22timestamp%22%3A1723655401520%7D
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?brand=phet-io&ea&postMessageOnError&sim=models-of-the-hydrogen-atom&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723654930805%22%2C%22timestamp%22%3A1723655401520%7D
[CONSOLE] enabling assert
[CONSOLE] Assertion failed:  required tandems must be supplied
[CONSOLE] Debug info: {
  "seed": 0.2807445494034533,
  "currentScreenName": "HomeScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/axon/js/ReadOnlyProperty.js:109:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/axon/js/Property.js:13:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/sun/js/buttons/ButtonModel.js:67:5)
    at new PushButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/sun/js/buttons/PushButtonModel.js:38:5)
    at new RectangularPushButton (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/sun/js/buttons/RectangularPushButton.js:37:29)
    at new AbsorptionWavelengthsDialog (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/models-of-the-hydrogen-atom/js/common/view/AbsorptionWavelengthsDialog.js:118:26)
    at new LightControlPanel (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/models-of-the-hydrogen-atom/js/common/view/LightControlPanel.js:37:41)
    at new SpectraScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/models-of-the-hydrogen-atom/js/spectra/view/SpectraScreenView.js:53:31)
    at SpectraScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/models-of-the-hydrogen-atom/js/spectra/SpectraScreen.js:28:82)
    at SpectraScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/joist/js/Sim.js:759:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/joist/js/Sim.js:768:21
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/axon/js/ReadOnlyProperty.js:109:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/axon/js/Property.js:13:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/sun/js/buttons/ButtonModel.js:67:5)
    at new PushButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/sun/js/buttons/PushButtonModel.js:38:5)
    at new RectangularPushButton (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/sun/js/buttons/RectangularPushButton.js:37:29)
    at new AbsorptionWavelengthsDialog (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/models-of-the-hydrogen-atom/js/common/view/AbsorptionWavelengthsDialog.js:118:26)
    at new LightControlPanel (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/models-of-the-hydrogen-atom/js/common/view/LightControlPanel.js:37:41)
    at new SpectraScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/models-of-the-hydrogen-atom/js/spectra/view/SpectraScreenView.js:53:31)
    at SpectraScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/models-of-the-hydrogen-atom/js/spectra/SpectraScreen.js:28:82)
    at SpectraScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/joist/js/Sim.js:759:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/chipper/dist/js/joist/js/Sim.js:768:21
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 8/14/2024, 11:02:10 AM

----------------------------------

models-of-the-hydrogen-atom : phet-io-data-stream-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/phet-io-wrappers/data-stream/?sim=models-of-the-hydrogen-atom&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723654930805%22%2C%22timestamp%22%3A1723655356093%7D
ERROR: Uncaught Error: Assertion failed: required tandems must be supplied
STACK: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/assert/js/assert.js:45:13)
    at assert (PhetioObject.ts:216:6)
    at initializePhetioObject (PhetioObject.ts:196:11)
    at  (ReadOnlyProperty.ts:176:4)
    at  (Property.ts:17:4)
    at  (BooleanProperty.ts:31:4)
    at  (EnabledProperty.ts:45:4)
    at  (EnabledComponent.ts:68:54)
    at  (ButtonModel.ts:108:4)
    at  (PushButtonModel.ts:80:4)
    at  (RectangularPushButton.ts:50:28)
    at  (AbsorptionWavelengthsDialog.ts:101:25)
    at  (LightControlPanel.ts:51:40)
    at  (SpectraScreenView.ts:62:30)
    at  (SpectraScreen.ts:40:15)
    at createView (Screen.ts:309:22)
    at initializeView (Sim.ts:914:15)
    at  (Sim.ts:922:25)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723654930805%2Fphet-io-wrappers%2Fdata-stream%2F%3Fsim%3Dmodels-of-the-hydrogen-atom%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723654930805%22%2C%22timestamp%22%3A1723655356093%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723654930805%2Fphet-io-wrappers%2Fdata-stream%2F%3Fsim%3Dmodels-of-the-hydrogen-atom%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723654930805%22%2C%22timestamp%22%3A1723655356093%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/phet-io-wrappers/data-stream/?sim=models-of-the-hydrogen-atom&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723654930805%22%2C%22timestamp%22%3A1723655356093%7D
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1723654930805/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?brand=phet-io&ea&postMessageOnError&sim=models-of-the-hydrogen-atom&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723654930805%22%2C%22timestamp%22%3A1723655356093%7D&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] Assertion failed:  required tandems must be supplied
[CONSOLE] Debug info: {
  "seed": 0.645919732341981,
  "currentScreenName": "HomeScreen"
}
```

**Comment by pixelzoom** [comment]
Thanks @KatieWoe. Fixed in the above commit. Closing.
