### ISSUE TITLE
CT ERROR: QUERY: brand=phet&ea&fuzz

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/models-of-the-hydrogen-atom#58]
```
models-of-the-hydrogen-atom : fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1724835065063%22%2C%22timestamp%22%3A1724835393594%7D&brand=phet&ea&fuzz
ERROR: QUERY: brand=phet&ea&fuzz
Uncaught Error: Assertion failed
STACK: Error: Assertion failed
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/assert/js/assert.js:45:13)
    at assert (SchrodingerQuantumNumbers.ts:252:12)
    at choose_l (SchrodingerQuantumNumbers.ts:101:18)
    at getNextState (SchrodingerModel.ts:97:55)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:343:22)
    at _notifyListeners (ReadOnlyProperty.ts:391:46)
    at notifyValueListeners (NumberProperty.ts:204:28)
    at setValueAndRange (NumberProperty.ts:213:9)
    at resetValueAndRange (NumberProperty.ts:177:9)
    at reset (BohrElectron.ts:106:19)
    at reset (BohrModel.ts:108:18)
    at reset (DeBroglieModel.ts:78:10)
    at reset (SchrodingerModel.ts:107:10)
    at reset (MOTHAModel.ts:146:24)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:343:22)
    at _notifyListeners (ReadOnlyProperty.ts:287:13)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1724835065063%2Fmodels-of-the-hydrogen-atom%2Fmodels-of-the-hydrogen-atom_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1724835065063%22%2C%22timestamp%22%3A1724835393594%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1724835065063%2Fmodels-of-the-hydrogen-atom%2Fmodels-of-the-hydrogen-atom_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1724835065063%22%2C%22timestamp%22%3A1724835393594%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1724835065063%22%2C%22timestamp%22%3A1724835393594%7D&brand=phet&ea&fuzz
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed
[CONSOLE] Debug info: {
  "seed": 0.44766944509762374,
  "currentScreenName": "SpectraScreen"
}
[PAGE ERROR] Error: Error: Assertion failed
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/assert/js/assert.js:45:13)
    at choose_l (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/SchrodingerQuantumNumbers.js:224:13)
    at SchrodingerQuantumNumbers.getNextState (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/SchrodingerQuantumNumbers.js:93:19)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/SchrodingerModel.js:81:56
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
    at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/ReadOnlyProperty.js:254:23)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/ReadOnlyProperty.js:299:47
    at NumberProperty.setValueAndRange (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/NumberProperty.js:159:29)
    at NumberProperty.resetValueAndRange (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/NumberProperty.js:168:10)
    at NumberProperty.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/NumberProperty.js:133:10)
    at BohrElectron.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/BohrElectron.js:86:20)
    at Experiment.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/BohrModel.js:85:19)
    at Experiment.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/DeBroglieModel.js:61:11)
    at Experiment.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/SchrodingerModel.js:89:11)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/MOTHAModel.js:101:25
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
    at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/ReadOnlyProperty.js:254:23)
    at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed:  reentry detected, value=experiment, oldValue=model
[CONSOLE] Debug info: {
  "seed": 0.44766944509762374,
  "currentScreenName": "SpectraScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=experiment, oldValue=model
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/assert/js/assert.js:45:13)
    at StringUnionProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/ReadOnlyProperty.js:252:15)
    at StringUnionProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
    at StringUnionProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/ReadOnlyProperty.js:183:12)
    at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/Property.js:48:11)
    at PressListener.release [as _releaseListener] (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/sun/js/ABSwitch.js:98:24)
    at PressListener.onRelease (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/listeners/PressListener.js:577:10)
    at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/tandem/js/PhetioAction.js:137:17)
    at PressListener.release (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/listeners/PressListener.js:350:25)
    at PressListener.pointerUp (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/listeners/PressListener.js:668:12)
    at Input.dispatchToListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/Input.js:1700:23)
    at Input.dispatchEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/Input.js:1658:10)
    at Input.upEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/Input.js:1486:10)
    at Input.touchEndAction.PhetioAction.phetioPlayback (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/Input.js:412:14)
    at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/tandem/js/PhetioAction.js:137:17)
    at Input.touchEnd (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/Input.js:1145:25)
    at InputFuzzer.touchEnd (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/InputFuzzer.js:225:25)
    at InputFuzzer.touchEndAction (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/InputFuzzer.js:55:12)
    at InputFuzzer.fuzzEvents (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/InputFuzzer.js:102:7)
    at SimDisplay.fuzzInputEvents (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/joist/js/SimDisplay.js:181:24)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed:  reentry detected, value=model, oldValue=experiment
[CONSOLE] Debug info: {
  "seed": 0.44766944509762374,
  "currentScreenName": "SpectraScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=model, oldValue=experiment
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/assert/js/assert.js:45:13)
    at StringUnionProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/ReadOnlyProperty.js:252:15)
    at StringUnionProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
    at StringUnionProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/ReadOnlyProperty.js:183:12)
    at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/axon/js/Property.js:48:11)
    at PressListener.release [as _releaseListener] (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/sun/js/ABSwitch.js:110:24)
    at PressListener.onRelease (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/listeners/PressListener.js:577:10)
    at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/tandem/js/PhetioAction.js:137:17)
    at PressListener.release (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/listeners/PressListener.js:350:25)
    at PressListener.pointerUp (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/listeners/PressListener.js:668:12)
    at Input.dispatchToListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/Input.js:1700:23)
    at Input.dispatchEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/Input.js:1658:10)
    at Input.upEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/Input.js:1486:10)
    at Input.mouseUpAction.PhetioAction.phetioPlayback (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/Input.js:280:12)
    at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/tandem/js/PhetioAction.js:137:17)
    at Input.mouseUp (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/Input.js:1076:24)
    at InputFuzzer.mouseToggle (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/InputFuzzer.js:255:27)
    at InputFuzzer.mouseToggleAction (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/InputFuzzer.js:40:12)
    at InputFuzzer.fuzzEvents (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/scenery/js/input/InputFuzzer.js:102:7)
    at SimDisplay.fuzzInputEvents (http://128.138.93.172/continuous-testing/ct-snapshots/1724835065063/chipper/dist/js/joist/js/SimDisplay.js:181:24)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 8/28/2024, 2:51:05 AM
```

**Comment by pixelzoom** [comment]
In the above commits, I added assertion messages. CT now reports:

> models-of-the-hydrogen-atom : fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1725041236249/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1725041236249%22%2C%22timestamp%22%3A1725045706266%7D&brand=phet&ea&fuzz
ERROR: QUERY: brand=phet&ea&fuzz
Uncaught Error: Assertion failed: lNew violates rules: n=1 l=0 lNew=1

So this violates the l = [0,n-1] constraint. 

I suspect that there's a bug in the Java version's state transition generation.

**Comment by pixelzoom** [comment]
@KatieWoe opened a duplicate of this issue, with the improved assertion message, see https://github.com/phetsims/models-of-the-hydrogen-atom/issues/59.  So we'll track in that issue, and close this issue.
