### ISSUE TITLE
CT: invalid wavefunction

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/models-of-the-hydrogen-atom#91]
```
models-of-the-hydrogen-atom : fuzz : unbuilt : listenerOrderRandom
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1735006737763%22%2C%22timestamp%22%3A1735008620030%7D&brand=phet&ea&fuzz&listenerOrder=random
ERROR: QUERY: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: invalid wavefunction: (1,1,-1
STACK: Error: Assertion failed: invalid wavefunction: (1,1,-1
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/assert/js/assert.js:45:21)
    at assert (../../../../../../../models-of-the-hydrogen-atom/js/common/model/SchrodingerQuantumNumbers.ts:76:14)
    at  (../../../../../../../models-of-the-hydrogen-atom/js/common/model/SchrodingerQuantumNumbers.ts:106:16)
    at getNextState (../../../../../../../models-of-the-hydrogen-atom/js/common/model/SchrodingerModel.ts:102:55)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:185:17)
    at emit (../../../../../axon/js/ReadOnlyProperty.ts:344:22)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:392:46)
    at notifyValueListeners (../../../../../axon/js/NumberProperty.ts:204:28)
    at setValueAndRange (../../../../../axon/js/NumberProperty.ts:213:9)
    at resetValueAndRange (../../../../../axon/js/NumberProperty.ts:177:9)
    at reset (../../../../../../../models-of-the-hydrogen-atom/js/common/model/BohrElectron.ts:105:19)
    at reset (../../../../../../../models-of-the-hydrogen-atom/js/common/model/BohrModel.ts:110:18)
    at reset (../../../../../../../models-of-the-hydrogen-atom/js/common/model/SchrodingerModel.ts:120:10)
    at reset (../../../../../../../models-of-the-hydrogen-atom/js/common/model/MOTHAModel.ts:158:24)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:185:17)
    at emit (../../../../../axon/js/ReadOnlyProperty.ts:344:22)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:288:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:268:11)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735006737763%2Fmodels-of-the-hydrogen-atom%2Fmodels-of-the-hydrogen-atom_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1735006737763%22%2C%22timestamp%22%3A1735008620030%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735006737763%2Fmodels-of-the-hydrogen-atom%2Fmodels-of-the-hydrogen-atom_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1735006737763%22%2C%22timestamp%22%3A1735008620030%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/models-of-the-hydrogen-atom/models-of-the-hydrogen-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1735006737763%22%2C%22timestamp%22%3A1735008620030%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[LOADED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735006737763%2Fmodels-of-the-hydrogen-atom%2Fmodels-of-the-hydrogen-atom_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22models-of-the-hydrogen-atom%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1735006737763%22%2C%22timestamp%22%3A1735008620030%7D
[CONSOLE] listenerOrder random seed: 708616
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed:  invalid wavefunction: (1,1,-1
[CONSOLE] Debug info: {
  "seed": 0.18805617085896564,
  "currentScreenName": "EnergyLevelsScreen",
  "secondsSinceSimStarted": 107.654
}
[PAGE ERROR] Error: Error: Assertion failed: invalid wavefunction: (1,1,-1
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/assert/js/assert.js:45:21)
    at new SchrodingerQuantumNumbers (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/SchrodingerQuantumNumbers.js:106:19)
    at SchrodingerQuantumNumbers.getNextState (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/SchrodingerQuantumNumbers.js:77:21)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/SchrodingerModel.js:149:62
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:86:13)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:65:30)
    at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:118:27)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:157:53
    at NumberProperty.setValueAndRange (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/NumberProperty.js:74:33)
    at NumberProperty.resetValueAndRange (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/NumberProperty.js:81:14)
    at NumberProperty.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/NumberProperty.js:53:14)
    at BohrElectron.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/BohrElectron.js:21:24)
    at SchrodingerModel.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/BohrModel.js:51:23)
    at SchrodingerModel.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/SchrodingerModel.js:56:15)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/models-of-the-hydrogen-atom/js/common/model/MOTHAModel.js:153:33
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:86:13)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:65:30)
    at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:118:27)
    at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:76:22)
    at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:60:18)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed:  reentry detected, value=[object Object], oldValue=[object Object]
[CONSOLE] Debug info: {
  "seed": 0.18805617085896564,
  "currentScreenName": "EnergyLevelsScreen",
  "secondsSinceSimStarted": 107.744
}
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/assert/js/assert.js:45:21)
    at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:116:19)
    at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:76:22)
    at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:60:18)
    at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/Property.js:37:15)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:107:52
    at TinyEmitter.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:86:13)
    at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:73:22)
    at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/Emitter.js:34:26)
    at RectangularRadioButton.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:29:31)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:111:22
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:86:13)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:65:30)
    at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:118:27)
    at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:76:22)
    at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:60:18)
    at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/Property.js:37:15)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/sun/js/buttons/ButtonModel.js:35:31
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:86:13)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:65:30)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed:  reentry detected, value=[object Object], oldValue=[object Object]
[CONSOLE] Debug info: {
  "seed": 0.18805617085896564,
  "currentScreenName": "EnergyLevelsScreen",
  "secondsSinceSimStarted": 108.221
}
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/assert/js/assert.js:45:21)
    at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:116:19)
    at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:76:22)
    at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:60:18)
    at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/Property.js:37:15)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:107:52
    at TinyEmitter.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:86:13)
    at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:73:22)
    at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/Emitter.js:34:26)
    at RectangularRadioButton.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:29:31)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:111:22
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:86:13)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:65:30)
    at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:118:27)
    at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:76:22)
    at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:60:18)
    at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/Property.js:37:15)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/sun/js/buttons/ButtonModel.js:35:31
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:86:13)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:65:30)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed:  reentry detected, value=[object Object], oldValue=[object Object]
[CONSOLE] Debug info: {
  "seed": 0.18805617085896564,
  "currentScreenName": "EnergyLevelsScreen",
  "secondsSinceSimStarted": 108.353
}
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/assert/js/assert.js:45:21)
    at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:116:19)
    at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:76:22)
    at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:60:18)
    at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/DerivedProperty.js:50:19)
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:86:13)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/TinyEmitter.js:65:30)
    at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:118:27)
    at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:76:22)
    at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/ReadOnlyProperty.js:60:18)
    at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/axon/js/Property.js:29:15)
    at ToggleSwitch.PhetioAction.parameters.validValues (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/sun/js/ToggleSwitch.js:150:28)
    at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/tandem/js/PhetioAction.js:43:21)
    at DragListener.end [as _end] (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/sun/js/ToggleSwitch.js:224:34)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/listeners/DragListener.js:135:31
    at DragListener.onRelease (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/listeners/PressListener.js:313:21)
    at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/tandem/js/PhetioAction.js:43:21)
    at DragListener.release (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/listeners/PressListener.js:123:29)
    at DragListener.release (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/listeners/DragListener.js:132:15)
    at DragListener.pointerUp (http://128.138.93.172/continuous-testing/ct-snapshots/1735006737763/chipper/dist/js/scenery/js/listeners/PressListener.js:387:18)
[CONSOLE] continuous-test-error

id: "Sparky Node Chrome"
Snapshot from 12/23/2024, 7:18:57 PM
```

**Comment by pixelzoom** [comment]
I've temporarily disabled this assertion until I can get to it.  This issue and #59 are related.

**Comment by pixelzoom** [comment]
This problem is occurring because I commented out the assertion that was causing https://github.com/phetsims/models-of-the-hydrogen-atom/issues/59.   I am now working on https://github.com/phetsims/models-of-the-hydrogen-atom/issues/59, and have re-enabled the assertion, so I'll close this issue.
